<?php

namespace AppBundle\Repository;

/**
 * AbsenceCompterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceCompterRepository extends \Doctrine\ORM\EntityRepository
{
}
