<?php

namespace AppBundle\Repository;

/**
 * CoefficientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoefficientRepository extends \Doctrine\ORM\EntityRepository
{
}
