<?php

namespace AppBundle\Repository;

/**
 * MainTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
