<?php

namespace AppBundle\Repository;

/**
 * StudentParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentParentRepository extends \Doctrine\ORM\EntityRepository
{
}
