services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    user.admin.user:
        class: UserBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, UserBundle:UserAdmin, "@fos_user.user_manager"]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Security, label: User }
        public: true
        
    user.admin_show_filter:
        class: UserBundle\Event\UserCustomAction
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.show, method: sonataAdminCheckUserRights }
    
    user.admin_form_filter:
        class: UserBundle\Event\UserCustomAction
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.form, method: sonataAdminCheckUserRights }
